apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syk-dig-oppgavelytter
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  image: {{ image }}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 400m
      memory: 768Mi
  kafka:
    pool: nav-prod
  azure:
    application:
      enabled: true
      tenant: nav.no
  envFrom:
    - secret: google-sql-syk-dig-backend-syk-dig-backend-syk-dig-opp-b187588a
  env:
    - name: CLOUD_SQL_INSTANCE
      value: teamsykmelding-prod-2acd:europe-north1:syk-dig-backend-db-instance
    - name: OPPGAVE_URL
      value: https://oppgave.prod-fss-pub.nais.io/api/v1/oppgaver
    - name: OPPGAVE_SCOPE
      value: api://prod-fss.oppgavehandtering.oppgave/.default
    - name: SAF_URL
      value: https://saf.prod-fss-pub.nais.io
    - name: SAF_SCOPE
      value: api://prod-fss.teamdokumenthandtering.saf/.default
    - name: OPPGAVE_TOPIC
      value: oppgavehandtering.oppgavehendelse-v1